### ISSUE TITLE
远程团队LodeStream的招聘信息

### ISSUE THREAD

**Issue by rankun203** [greatghoul/remote-working#124]
@greatghoul 这是招聘信息的内容，三个岗位在一页中，打开后有每个岗位单独的介绍，可以分开帖子发，所以由你决定要怎么发。另外我们之前在v2ex跟一早一晚有发过。

标题：

> Remote Freelance Jobs @ LodeStream.com (PT/FT/Project-Based) 远程自由职业（兼职/全职/项目制）

内容：

> LodeStream is a professional web/app development team based out in Seattle, US and Chengdu, CN with great entrepreneurial mindset that has been taking up projects globally especially in the US and China. We're starting a new batch of hiring (locations: China, Taiwan, Malaysia) for various positions to work on our new projects. Please follow the form links below and fill out the application form(s) if interested:
> 
> LodeStream是一组带有创业心态的专业技术开发团队（HQ成立于美国西雅图以及子公司四川成都），提供网页／网站及手机端应用建设服务，承接的业务为国际（主要为中国和美国）软件外包项目。现招聘新一批的远程工作职位（地理位置：大陆、台湾、马来西亚），有兴趣者请点击以下链接提交应聘表单给我们：
> 
> - [Assistant PM/Virtual Assistant 项目经理助理/远程助理 (Asia)](https://lodestreams.typeform.com/to/HhVlZU)
> - [Graphic/UI/UX Designer 平面/用户界面/用户体验设计师 (Asia)](https://lodestreams.typeform.com/to/TKRq6n)
> - [Web/Mobile Developer 网页/移动端程序员 (Asia)](https://lodestreams.typeform.com/to/Qgqf9U)
> 
> Other positions please visit https://xwiki.lodestream.com/careers or http://xwikicn.lodestream.com/careers. For more info or other questions please contact WeChat ID: lodestreams, or email hr@lodestream.com.
> 
> 其他职位请浏览 https://xwiki.lodestream.com/careers 或 http://xwikicn.lodestream.com/careers 。欲咨询其他问题请联系微信号：`lodestreams`，或来函致邮箱：hr@lodestream.com。

**Comment by greatghoul** [comment]
这个 Issue 就可以了，保留这个 Issue，等你们招聘结束，再关闭它。

我会帮你们在其它渠道再推一下。

**Comment by rankun203** [comment]
@greatghoul 对了，上面是所有职位在一起的帖子，除了开发者，我们也招设计师跟项目经理助理，我下面将三个单独职位的帖子发一下：

## Assistant PM

> **Remote Assistant Project Manager @ LodeStream.com (PT/FT/Project-Based) 远程项目经理助理/远程助理（兼职/全职/项目制）**

> LodeStream is a professional web/app development team based out in Seattle, US and Chengdu, China. We're currently looking for Assistant PM/Virtual Assistant positions to be filled. Please use the form link below to submit your application to us:
> 
> LodeStream是一组带有创业心态的专业技术开发团队（母公司成立于美国西雅图以及子公司在四川成都）。现招聘项目经理助理/远程助理，有兴趣者请点击以下链接提交应聘表单给我们：
> 
> Assistant PM/Virtual Assistant 项目经理助理/远程助理 (Asia): https://lodestreams.typeform.com/to/HhVlZU
> 
> Other positions please visit https://xwiki.lodestream.com/careers or http://xwikicn.lodestream.com/careers. For more info or other questions please contact WeChat ID: lodestreams, or email hr@lodestream.com.
> 
> 其他职位请浏览https://xwiki.lodestream.com/careers或http://xwikicn.lodestream.com/careers。欲咨询其他问题请联系微信号：lodestreams，或来函致邮箱：hr@lodestream.com。
> 
> Pay can be flexible and is determined case-by-case.

**Comment by rankun203** [comment]
## Web/Mobile Developer

> Remote Web/Mobile Developer @ LodeStream.com (PT/FT/Project-Based) 远程网页/移动端程序员（兼职/全职/项目制）

> LodeStream is a professional web/app development team based out in Seattle, US and Chengdu, China. We're currently looking for Web/Mobile Developer positions to be filled. Please use the form link below to submit your application to us:
> 
> LodeStream是一组带有创业心态的专业技术开发团队（母公司成立于美国西雅图以及子公司在四川成都）。现招聘网页/移动端程序员，有兴趣者请点击以下链接提交应聘表单给我们：
> 
> Web/Mobile Developer 网页/移动端程序员 (Asia): https://lodestreams.typeform.com/to/Qgqf9U
> 
> Other positions please visit https://xwiki.lodestream.com/careers or http://xwikicn.lodestream.com/careers. For more info or other questions please contact WeChat ID: lodestreams, or email hr@lodestream.com.
> 
> 其他职位请浏览https://xwiki.lodestream.com/careers或http://xwikicn.lodestream.com/careers。欲咨询其他问题请联系微信号：lodestreams，或来函致邮箱：hr@lodestream.com。

**Comment by rankun203** [comment]
## Graphic/UI/UX Designer

> Remote Graphic/UI/UX Designer @ LodeStream.com (PT/FT/Project-Based) 远程平面/用户界面/用户体验设计师（兼职/全职/项目制）

> LodeStream is a professional web/app development team based out in Seattle, US and Chengdu, China. We're currently looking for Graphic/UI/UX Designer positions to be filled. Please use the form link below to submit your application to us:
> 
> LodeStream是一组带有创业心态的专业技术开发团队（母公司成立于美国西雅图以及子公司在四川成都）。现招聘平面/用户界面/用户体验设计师，有兴趣者请点击以下链接提交应聘表单给我们：
> 
> Graphic/UI/UX Designer 平面/用户界面/用户体验设计师 (Asia)：https://lodestreams.typeform.com/to/TKRq6n
> 
> Other positions please visit https://xwiki.lodestream.com/careers or http://xwikicn.lodestream.com/careers. For more info or other questions please contact WeChat ID: lodestreams, or email hr@lodestream.com.
> 
> 其他职位请浏览https://xwiki.lodestream.com/careers或http://xwikicn.lodestream.com/careers。欲咨询其他问题请联系微信号：lodestreams，或来函致邮箱：hr@lodestream.com。

**Comment by rankun203** [comment]
@greatghoul 你好，因为这个post中我们不单招一个岗位，目前web全栈、设计师、助理尚未招到合适人选，希望可以再打开一段时间。

**Comment by rankun203** [comment]
@greatghoul 思考再三，觉得将不同职位发在同一个issue里不利于后期在某个职位找到人选后单独close，我们在考虑将不同职位的issue分开发布，找到合适人选的就close掉。
