### ISSUE TITLE
有没有可以帮国外公司给国内个人发放工资的公司？

### ISSUE THREAD

**Issue by freewind** [greatghoul/remote-working#154]
国外（美国）有一家公司想聘用国内的一些开发人员远程办公，但是由于一些法务政策方面的原因（比如在国内没有分公司），无法给个人发放工资。不知道国内有没有公司可以帮忙解决这样的问题？希望大家能推荐一下，谢谢

**Comment by think2011** [comment]
我做过的是直接个人转账，或者通过很快的但据说费用高的 Transferwise 直接 RMB 到账。
社保之类的自行处理

**Comment by greatghoul** [comment]
看群里有人推荐 派安盈

**Comment by freewind** [comment]
谢谢两位的推荐。可能是我没有表达清楚，这家公司因为其法务部门的要求，不允许直接向个人发放。所以就需要有一个中间公司，大概流程是：国内开发者名义上加入中间公司 ->  中间公司与该公司签合同 -> 国内开发者为该公司提供服务 -> 该公司向中间公司支付费用 -> 中间公司收取佣金 -> 中间公司给国内开发者发放工资。之前曾经找过一些公司，但感觉不太好，所以想再试试其他的，但是缺少这方面的信息和资源

**Comment by greatghoul** [comment]
你在一早一晚社区的微信群里面吗？不在的话，我加你进去，里面可能会有人了解。 @freewind

**Comment by freewind** [comment]
谢谢，我不在群里，可以帮忙加一下我。具体怎么操作？

**Comment by greatghoul** [comment]
@freewind 加我微信`greatghoul` 注明一早一晚，我拉你。

**Comment by carloxwang** [comment]
我们可以协助，我们过去两年服务了很多类似需求的企业，可以加我微信细谈 carloxwang

**Comment by qyf404** [comment]
这不就是离岸外包公司干的事情么? 可以问问大点的外包服务公司.

**Comment by terranc** [comment]
转BTC吧

**Comment by greatghoul** [comment]
BTC 不靠谱吧，个人也需要稳定的收入流水，这在买房等事件上也挺重要的，能有个稳定的公司代发工资还是挺好的，省不少事情。

**Comment by terranc** [comment]
买房只看最近6个月的流水，如果最近打算买房，自己上心，每月固定做好入金流水就好了啊，我的经验来说一个良好的征信比流水重要N倍。

**Comment by muyexi** [comment]
@freewind 那找劳务派遣公司就可以了

**Comment by fuzheng1998** [comment]
payoneer 怎么样

**Comment by freewind** [comment]
Slasify很棒，强烈推荐
