### ISSUE TITLE
Coderbunker 自由职业者社区（求加入“社区”和“远程团队”板块）

### ISSUE THREAD

**Issue by andiechu** [greatghoul/remote-working#186]
我目前是一个自由前端开发，混迹在 Coderbunker（[https://www.coderbunker.com/](https://www.coderbunker.com/)）社区。个人很喜欢这个社区的环境，也觉得这个社区有很多机会，但是貌似我身边的中国人都不太了解，所以来这里介绍一下，说不定能给很多寻找自由职业的童鞋们带来更多机会。

## 什么是 Coderbunker

是一个自由职业者随时可以过来交流的社区，也是一个帮助自由职业者发展的国际化平台。除了能够为自由职业者争取更好的薪资外，还有各种 co-learning、co-living、co-fitness 的活动，帮助自由职业者建立更健康的体格、更响亮的个人品牌。

另外，我们还自己有客户项目，并非一个单纯的“外包”团队，我们一直想做、也在做的事是：**用更自由的方式建立一个完整的新型研发团队**。我们把外包公司的抽成平摊到自由职业者本身的薪资中，运用现代软件管理帮助客户管理预算花销。也正因为我们并不只是接单，我们的项目中，涉及到很多 R&D 的内容，而不仅仅是单纯套用框架的简单项目。

## 宗旨

* 去中心化：目前除了上海本部，还有伦敦、蒙特利尔和布宜诺斯艾利斯三个团队。每个团队只要 fork Coderbunker 的管理模型，共享和拓展 Coderbunker 的成员及客户 pool，以及举办活动运营自己城市的分支
* 全透明：所有客户机会、财务管理全部向内部成员开放
* 预付模式合作：为了保证自由职业者的利益，想和我们合作的客户必须每月先支付当月的经费
* 非盈利：抽取的10%客户经费只用于建设 Coderbunker 社区，包括内部自动化系统、活动管理等，每笔支出向全体成员公开
* Zero-waste：必须要环保，争取少产出不可回收和降解的垃圾
* 另附加一个 Founder 的技术偏好：
    * 极其热爱 GraphQL，偏好 Python、Node.JS，React > Vue（emmm），Docker，热爱 Google 系列产品
    * 讨厌 MongoDB、Java
    * 喜欢搞先锋式的架构设计，比如把 web 后端直接砍掉、让 Chrome 浏览器跑 Python 代码什么的……

## 我们都有啥

* co-working：一起做项目赚钱啊
* co-learning：一起学习，提高自我。这个项目有以下几种方式
    * 每周末或晚上的 workshop：各种几个小时的小课
    * co-learning program：几个人一起学习，监督彼此的学习进度。目前主要是数据科学（以及 Python 机器学习）、JS 学的人比较多
    * 一对一导师指导
* events：比如为创业者们准备的创业讲座、一些主题性的演讲（比如如何把产品游戏化等等）、晚上播放电影（前几周都在放《权游》最后一季）、Hackathon……
* 每个分支都有自己的共享办公空间，上网的方法很科学，提供外接显示器等符合程序员的工作方式

### 大型公司

这类我们更像是劳务派遣或者外包公司了。没啥好讲的，就是客户有名一点、经费充足一点……

LVMH集团、DLG集团、迪卡侬……

### 创业公司

我们对于创业公司，以下两个创业公司都只有一个 CEO，开发、市场等都交给我们来做。另外我们还帮助这些创业公司寻找 partner 和投资人，对于这类客户，我们做的更像是一个“孵化器”。

[Overhand Fitness](http://overhandfitness.cn/)：已经被 SOSV 旗下的中国加速投资，我们帮助 CEO 完成了从软件到硬件的研发，而不仅仅只是“做个 demo”
[Atlas AI](http://www.atlasaitech.com/)：我们帮助 Atlas AI 做过驾驶行为预测的 iOS/Android app，web AR 室内导航，以及游戏化社区

### 编程导师项目

我们会根据学员的预算和个人需求，提供相应的有经验的成员做他们的导师。除了学习以外，我们还提供实际的项目让他们实习，指导他们如何真正在团队中进行软件开发，帮助他们获得真实的工作经验。

### 其他

* 实习项目：国内外的某几所高中、技术类学校合作项目
* 创业指导：主要是我们的创始人针对某些大学和创业者的项目

## 坐标

上海市徐汇区番禺路1199弄8号楼地下Agora Space

## 如果你符合以下的条件，欢迎加入我们

* **可以进行英语交流** （如果不能流畅的英语沟通，还是不要申请了，因为没办法和大家交流，也听不懂工作任务……）
* 会用科学的上网方式，有国际视野
* 认同我们的社区文化
* 善于沟通和交付任务
* 技术好，包括但不限于：
    * web 开发前、后端
    * 数据科学家
    * DevOps
    * iOS / Android 客户端开发 
    * 区块链开发
    * Unity 游戏开发
    * （非技术类）UX 设计
    * （非技术类）UI 设计，要求审美好
    * （非技术类）市场或社区运营，了解外国市场
* 最好在上海。不在上海也可以来上海不定期交流，我们支持远程工作，但是最好还是可以来偶尔坐下交流感情

可以联系我：am.freelancer@coderbunker.com

**Comment by greatghoul** [comment]
已经将你们加入到 ”远程团队“ 中了，不过我没有看到你们公开的交流社区的链接，所以并没有加入到 ”交流社区" 中。

**Comment by andiechu** [comment]
> 已经将你们加入到 ”远程团队“ 中了，不过我没有看到你们公开的交流社区的链接，所以并没有加入到 ”交流社区" 中。

谢谢。我们算是线下社区，或者社群，暂时没有网上的公开社区平台。

**Comment by greatghoul** [comment]
那官方的那个 Join us 表单填写之后就是申请加入社群，而不是 “应聘” 喽？

**Comment by andiechu** [comment]
> 那官网的那个 Join us 表单填写之后就是申请加入社群，而不是 “应聘” 喽？

嗯嗯是的

**Comment by muyexi** [comment]
@andiechu 怎么参与到Coderbunker的项目中？

**Comment by yuruwang** [comment]
您好，给您发了邮件，望回复
