### ISSUE TITLE
哪些开发语言的使用者比较好找到远程工作？

### ISSUE THREAD

**Issue by ACChe** [greatghoul/remote-working#35]

**Comment by ryan715** [comment]
英语。

**Comment by greatghoul** [comment]
国外什么语言找远程工作或许都能找到，国内的就不同了，因为这种工作模式还没有广泛接受，所以只有一些比较小，比较酷的团队才会使用这种工作方式，技术新，偏全栈。

NodeJS, Ruby on Rails, Python 都是相对比较好找的。iOS 和 Android 也不少。
