### ISSUE TITLE
日本或者台湾的一些远程工作或者兼职或者工作的...链接失效

### ISSUE THREAD

**Issue by Shineee** [greatghoul/remote-working#39]
日本或者台湾的一些远程工作或者兼职或者工作的，大家要警惕了
这个连接已经失效了，博主改一下

**Comment by mittya** [comment]
@Shineee  哪篇失效了可以直接提交一个 PR 来修改它 :wink:

**Comment by greatghoul** [comment]
原文章删除了，虽然能够找到副本，但考虑到这篇帖子虽然有可以参考的地方，但也有一定的地域问题，还是移除吧。
