### ISSUE TITLE
远程工作还有云沃客平台

### ISSUE THREAD

**Issue by srddpzbx** [greatghoul/remote-working#46]
为啥大鲲的入选了.云沃客没入选呢.

**Comment by greatghoul** [comment]
我是偶尔听说一个就加一个，如果云活客也是远程工作的平台，欢迎提交 PR

**Comment by greatghoul** [comment]
我是偶尔听说一个就加一个，如果云沃客也是远程工作的平台，欢迎提交 PR

**Comment by srddpzbx** [comment]
www.clouderwork.com
这是一个新的平台.有点像upwork

发自拥有无穷力量的手持移动通话终端 🍎6
